server:
  port: 9001

spring:
  application:
    name: joy-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/joy?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  config-location: classpath:mapper/config/mybatis-config.xml
  type-aliases-package: com.cy.joy.pojo
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: joy-user-9001
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ConnectTimeout: 30000 # 连接超时时间(ms)
  ReadTimeout: 120000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

info:
  app.name: cy-joy
  company.name: www.cy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

wx:
  mp:
    configs:
      - appId: wxee335ca9d1cf9d9f
        secret: 91dbfd4ecad98810332f601468b88bb5
        token: cytoken
        aesKey: