server:
  port: 9527

spring:
  application:
    name: joy-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: joy-gateway-9527
    prefer-ip-address: true

zuul:
  retryable: true
  routes:
    joy-product:
      path: /joy-product/**
      serviceId: joy-product
    joy-cart:
      path: /joy-cart/**
      serviceId: joy-cart
    joy-order:
      path: /joy-order/**
      serviceId: joy-order
    joy-user:
      path: /joy-user/**
      serviceId: joy-user

info:
  app.name: cy-joy
  company.name: www.cy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
