server:
  port: 9527

spring:
  application:
    name: joy-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: joy-gateway-9527
    prefer-ip-address: true

#负载均衡配置
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 120000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1

#熔断的延迟时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

zuul:
  retryable: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000
  routes:
    joy-product:
      path: /joy-product/**
      serviceId: joy-product
    joy-cart:
      path: /joy-cart/**
      serviceId: joy-cart
    joy-order:
      path: /joy-order/**
      serviceId: joy-order
    joy-user:
      path: /joy-user/**
      serviceId: joy-user

info:
  app.name: cy-joy
  company.name: www.cy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#自定义内容
sc:
  jwt:
    pubKeyPath: D:/rsa/rsa.pub # 公钥地址
  filter:
    allowPaths:
      - /wxCallBack
      - /list
